export const ProductsList = [
  {
    id: 1,
    name: "Шуба из соболя Флориана",
    image: "link_to_image.jpg",
    description: "Роскошная норковая шуба.",
    category: "Соболь",
    price: 1500,
  },
  {
    id: 2,
    name: "Шуба из меха норки",
    image: "link_to_image2.jpg",
    description: "Идеальный выбор для зимы.",
    category: "Шиншилла",
    price: 2500,
  },
  {
    id: 3,
    name: "Шуба из чего-то",
    image: "link_to_image3.jpg",
    description: "Идеальный выбор для вас.",
    category: "Рысь",
    price: 3500,
  },
  {
    id: 4,
    name: "Шуба из соболя Флориана",
    image: "link_to_image.jpg",
    description: "Роскошная норковая шуба.",
    category: "Соболь",
    price: 1500,
  },
  {
    id: 5,
    name: "Шуба из меха норки",
    image: "link_to_image2.jpg",
    description: "Идеальный выбор для зимы.",
    category: "Шиншилла",
    price: 2500,
  },
  {
    id: 6,
    name: "Шуба из чего-то",
    image: "link_to_image3.jpg",
    description: "Идеальный выбор для вас.",
    category: "Рысь",
    price: 3500,
  },
];
